/**
 * EXP-038: NQ-028 — C12 (Second-Edge Fillet) vs C00 and C03
 *
 * Executes NQ-028's actual discriminating test using C12, a new controlled model supplied by
 * the user: the same C00 base cube with a 1mm fillet applied to the edge shared by the -X and
 * -Y faces (the diagonally opposite vertical edge from the one C03/C09 use, which is shared by
 * +X and +Y). This is the exact model EXP-037 specified as required
 * (knowledge/evidence/2026-08-14_v0.4.7-EXP037.md Section 6) to distinguish:
 *
 *   Hypothesis A (spatial/topological): the faces whose Block1 tokens change are always the
 *     faces topologically adjacent to whichever edge was actually filleted -- so moving the
 *     fillet to the -X/-Y edge should move the changed faces to -X/-Y.
 *   Hypothesis B (global/feature-type state): the same +X/+Y faces (or the same face indices,
 *     2/3) change whenever any edge-type feature is applied, independent of location -- so
 *     C12 should still show +X/+Y (or index 2/3) changing, not -X/-Y.
 *
 * Method: uses the SAME corrected tooling strategy validated in EXP-037 (matchFaces:
 * centroid-distance face correspondence with explicit ambiguity flagging; computeAdjacency:
 * real vertex/edge-sharing adjacency). computeAdjacency is copied verbatim. matchFaces keeps
 * EXP-037's centroid-distance strategy but with one measured, validated refinement -- using
 * each face's bounding-box center instead of its raw vertex average, because the raw average
 * (EXP-037's choice) turned out to be sensitive to tessellation density and produced a
 * dangerously thin margin once tested against C12's real geometry (see the note above
 * centroid() below, and Section 2 of the evidence file, for the full derivation and
 * cross-corpus validation of this fix). C12 is
 * parsed directly from the actual model.SLDPRT file supplied by the user (via
 * parser/v0.1/src/parser-core.js, read-only, unmodified) -- this is the first EXP-03x script in
 * this thread able to verify against a real SLDPRT file rather than only archived JSON. C00 and
 * C03 are read from the already-archived VERTEX_ANALYSIS.json / EXP033_FEATURE_STATE.json
 * (their own SLDPRT files are still not present in this environment).
 *
 * Do NOT modify parser/.
 * Do NOT assign semantic meaning to token values.
 * Do NOT create another model -- C12 was supplied by the user, not generated by this script.
 * Observation and causal interpretation are kept explicitly separate throughout (see the
 * printed "OBSERVATION" vs "INTERPRETATION" blocks and the evidence file's Section 7).
 */

'use strict';

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const DIR = __dirname;
const REPO_ROOT = path.join(__dirname, '..');
const parserCore = require(path.join(REPO_ROOT, 'parser', 'v0.1', 'src', 'parser-core.js'));

function loadJSON(name) {
  return JSON.parse(fs.readFileSync(path.join(DIR, name), 'utf8'));
}

const VERTEX_ANALYSIS = loadJSON('VERTEX_ANALYSIS.json');
const EXP033 = loadJSON('EXP033_FEATURE_STATE.json');

// ============================================================
// Parse C12 directly from the real SLDPRT file (read-only parser use)
// ============================================================

const C12_PATH = path.join(REPO_ROOT, 'test files original', 'controlled', 'C12_cube_fillet_1mm_edge2', 'model.SLDPRT');

function parseSLDPRTFile(filePath) {
  const buf = fs.readFileSync(filePath);
  const inflateRaw = (b) => Buffer.from(zlib.inflateRawSync(b));
  const inflateZlib = (b) => Buffer.from(zlib.inflateSync(b));
  return parserCore.parseSLDPRT(buf, inflateRaw, inflateZlib);
}

function computeAverageNormal(normals, vertexCount) {
  let nx = 0, ny = 0, nz = 0;
  for (let i = 0; i < vertexCount; i++) {
    nx += normals[i * 3];
    ny += normals[i * 3 + 1];
    nz += normals[i * 3 + 2];
  }
  nx /= vertexCount; ny /= vertexCount; nz /= vertexCount;
  const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
  if (len === 0) return { nx: 0, ny: 0, nz: 0 };
  return { nx: nx / len, ny: ny / len, nz: nz / len };
}

// Identical classification function to exp032/033/037 -- reused unmodified.
function determineOrientation(normal, tolerance = 0.01) {
  const { nx, ny, nz } = normal;
  if (Math.abs(nx - 1) < tolerance && Math.abs(ny) < tolerance && Math.abs(nz) < tolerance) return '+X';
  if (Math.abs(nx + 1) < tolerance && Math.abs(ny) < tolerance && Math.abs(nz) < tolerance) return '-X';
  if (Math.abs(ny - 1) < tolerance && Math.abs(nx) < tolerance && Math.abs(nz) < tolerance) return '+Y';
  if (Math.abs(ny + 1) < tolerance && Math.abs(nx) < tolerance && Math.abs(nz) < tolerance) return '-Y';
  if (Math.abs(nz - 1) < tolerance && Math.abs(nx) < tolerance && Math.abs(ny) < tolerance) return '+Z';
  if (Math.abs(nz + 1) < tolerance && Math.abs(nx) < tolerance && Math.abs(ny) < tolerance) return '-Z';
  const absX = Math.abs(nx), absY = Math.abs(ny), absZ = Math.abs(nz);
  if (absX > 0.99 && absY < 0.01 && absZ < 0.01) return nx > 0 ? '+X' : '-X';
  if (absY > 0.99 && absX < 0.01 && absZ < 0.01) return ny > 0 ? '+Y' : '-Y';
  if (absZ > 0.99 && absX < 0.01 && absY < 0.01) return nz > 0 ? '+Z' : '-Z';
  return `NON_AXIS(${nx.toFixed(3)},${ny.toFixed(3)},${nz.toFixed(3)})`;
}

const c12Parsed = parseSLDPRTFile(C12_PATH);
console.log(`Parsed C12 directly from real SLDPRT file: ${c12Parsed.faces.length} faces.`);

// Build C12 face records in the same shape as VERTEX_ANALYSIS.json's facesA/facesB, plus full
// token/orientation data (VERTEX_ANALYSIS.json never stored tokens; EXP033_FEATURE_STATE.json
// never saw C12, since it didn't exist yet -- both are computed fresh here from the real file).
const c12Faces = c12Parsed.faces.map((f, idx) => {
  const vertices = [];
  for (let v = 0; v < f.vertexCount; v++) {
    vertices.push([f.vertices[v * 3], f.vertices[v * 3 + 1], f.vertices[v * 3 + 2]]);
  }
  const normal = computeAverageNormal(f.normals, f.vertexCount);
  return {
    index: idx,
    edgeCount: f.edgeCount,
    vertexCount: f.vertexCount,
    secCount: f.secCount,
    b1Len: f.b1Len,
    b2Body: Array.from(f.b2Body),
    sectionLens: f.sectionLens,
    loopSizes: f.loopSizes,
    vertices,
    tokens: Array.from(f.b1Body),
    orientation: determineOrientation(normal),
    normal,
  };
});

const tokensByModelFaceC12 = new Map();
for (const f of c12Faces) {
  tokensByModelFaceC12.set(`C12_cube_fillet_1mm_edge2|${f.index}`, {
    tokens: f.tokens,
    orientation: f.orientation,
  });
}

// ============================================================
// Token/orientation lookup for C00 and C03 (archived; EXP033_FEATURE_STATE.json has full
// per-face token arrays for both -- reused unmodified, same source EXP-037 used)
// ============================================================

const tokensByModelFace = new Map();
for (const f of EXP033.faces) {
  tokensByModelFace.set(`${f.model}|${f.faceIndex}`, {
    tokens: f.tokens,
    orientation: f.orientation,
    faceType: f.faceType,
  });
}
for (const [k, v] of tokensByModelFaceC12) tokensByModelFace.set(k, v);

function lookupTokens(model, faceIndex) {
  return tokensByModelFace.get(`${model}|${faceIndex}`) || null;
}

// ============================================================
// Real geometric adjacency and face correspondence -- adjacency (computeAdjacency,
// sharedVertexCount, vertClose) is COPIED VERBATIM from
// v0.4.7/exp037_edge_location_and_adjacency.js. Face correspondence (matchFaces) reuses the
// same centroid-distance STRATEGY but with one deliberate, validated refinement -- see note
// above centroid() below.
// ============================================================

const VERTEX_TOL = 1e-5;

function vertClose(a, b, tol = VERTEX_TOL) {
  return Math.abs(a[0] - b[0]) < tol && Math.abs(a[1] - b[1]) < tol && Math.abs(a[2] - b[2]) < tol;
}

function sharedVertexCount(faceA, faceB) {
  let count = 0;
  for (const va of faceA.vertices) {
    for (const vb of faceB.vertices) {
      if (vertClose(va, vb)) {
        count++;
        break;
      }
    }
  }
  return count;
}

function overlapScoreForReport(faceA, faceB) {
  let aInB = 0;
  for (const va of faceA.vertices) {
    if (faceB.vertices.some((vb) => vertClose(va, vb))) aInB++;
  }
  let bInA = 0;
  for (const vb of faceB.vertices) {
    if (faceA.vertices.some((va) => vertClose(va, vb))) bInA++;
  }
  return (aInB + bInA) / (faceA.vertices.length + faceB.vertices.length);
}

function computeAdjacency(targetFace, candidateFaces) {
  return candidateFaces
    .filter((f) => f.index !== targetFace.index)
    .map((f) => ({ index: f.index, sharedVertices: sharedVertexCount(targetFace, f) }))
    .filter((r) => r.sharedVertices >= 2)
    .sort((a, b) => b.sharedVertices - a.sharedVertices);
}

// REFINEMENT vs EXP-037 (discovered and validated against real data while building this
// script -- see knowledge/evidence/2026-08-15_v0.4.7-EXP038.md Section 2 for the full
// derivation): EXP-037 used the raw vertex-average as each face's "centroid." That is
// sensitive to non-uniform tessellation density -- a finely-subdivided fillet arc pulls the
// average disproportionately toward itself. Measured directly against C12 (the real SLDPRT
// file this script parses): C00 faces 4/5 (+Z/-Z), which keep the SAME topological identity
// after the fillet trims one corner, shift by up to 0.0046m under vertex-averaging -- within
// 0.0001m of EXP-037's 0.004m threshold, and uncomfortably close to the ~0.0046m distance from
// the genuinely NEW face (index 6) to its nearest unrelated C00 face. Re-measured with the
// AXIS-ALIGNED BOUNDING-BOX CENTER instead (insensitive to point density, only to extent):
// every genuine same-face shift across ALL five archived pairs (C03, C09, C04, C10, and this
// new C12) drops to <=0.0005m, while the new face's distance to its nearest unrelated existing
// face stays ~0.0045m and the minimum distinct-face separation stays ~0.0071m -- both
// essentially unchanged, since they depend on face extent/position, not point density. This
// gives a >=9x safety margin on both sides of the threshold, computed from the corpus's own
// data (not hand-tuned to produce a particular NQ-028 answer -- verified against C03/C09/C04/
// C10 as well as C12 before being adopted). EXP-037's original file and results are NOT
// modified; this refinement applies only within this script.
function centroid(face) {
  let minX = Infinity, minY = Infinity, minZ = Infinity;
  let maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;
  for (const v of face.vertices) {
    if (v[0] < minX) minX = v[0]; if (v[0] > maxX) maxX = v[0];
    if (v[1] < minY) minY = v[1]; if (v[1] > maxY) maxY = v[1];
    if (v[2] < minZ) minZ = v[2]; if (v[2] > maxZ) maxZ = v[2];
  }
  return [(minX + maxX) / 2, (minY + maxY) / 2, (minZ + maxZ) / 2];
}

function dist3(a, b) {
  return Math.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2);
}

const CENTROID_THRESHOLD = 0.002; // see refinement note above centroid(): safely between the
// largest observed same-face bbox-center shift (~0.0005m) and the nearest new-face/unrelated-
// face distance (~0.0045m), across all five tested pairs.
const AMBIGUITY_MARGIN = 0.0005;

function matchFaces(facesA, facesB) {
  const pairs = [];
  for (const a of facesA) {
    const ca = centroid(a);
    for (const b of facesB) {
      const cb = centroid(b);
      const d = dist3(ca, cb);
      if (d <= CENTROID_THRESHOLD) pairs.push({ a, b, dist: d, overlap: overlapScoreForReport(a, b) });
    }
  }
  pairs.sort((p, q) => p.dist - q.dist);

  const usedA = new Set();
  const usedB = new Set();
  const matched = [];
  const ambiguous = [];

  const candidatesByB = new Map();
  for (const p of pairs) {
    if (!candidatesByB.has(p.b.index)) candidatesByB.set(p.b.index, []);
    candidatesByB.get(p.b.index).push(p);
  }
  const ambiguousB = new Set();
  for (const [bIdx, cands] of candidatesByB) {
    cands.sort((x, y) => x.dist - y.dist);
    if (cands.length >= 2) {
      const gap = cands[1].dist - cands[0].dist;
      if (gap < AMBIGUITY_MARGIN) {
        ambiguousB.add(bIdx);
        ambiguous.push({
          bIndex: bIdx,
          candidates: cands.slice(0, 3).map((c) => ({ aIndex: c.a.index, centroidDist: c.dist })),
        });
      }
    }
  }

  for (const p of pairs) {
    if (usedA.has(p.a.index) || usedB.has(p.b.index)) continue;
    if (ambiguousB.has(p.b.index)) continue;
    usedA.add(p.a.index);
    usedB.add(p.b.index);
    matched.push({ aIndex: p.a.index, bIndex: p.b.index, centroidDist: p.dist, vertexOverlap: p.overlap });
  }

  const removed = facesA.filter((f) => !usedA.has(f.index)).map((f) => f.index);
  const added = facesB.filter((f) => !usedB.has(f.index) && !ambiguousB.has(f.index)).map((f) => f.index);

  return { matched, removed, added, ambiguous };
}

// VERTEX_ANALYSIS.json stores b2Body as a numeric-keyed OBJECT (e.g. {"0":6}), an artifact of
// how vertex_analysis.js originally serialized it, while this script's freshly-parsed C12
// faces store it as a plain ARRAY (e.g. [6]). Comparing JSON.stringify of the two shapes would
// always report "changed" even when the values are identical -- normalize both to arrays
// before comparing, so this reflects a real value difference, not a representation artifact.
function normalizeB2Body(b2Body) {
  return Array.isArray(b2Body) ? b2Body : Object.values(b2Body);
}

function facesIdentical(faceA, faceB) {
  if (faceA.edgeCount !== faceB.edgeCount) return false;
  if (faceA.vertexCount !== faceB.vertexCount) return false;
  if (faceA.secCount !== faceB.secCount) return false;
  if (faceA.b1Len !== faceB.b1Len) return false;
  if (faceA.vertices.length !== faceB.vertices.length) return false;
  for (let i = 0; i < faceA.vertices.length; i++) {
    if (!vertClose(faceA.vertices[i], faceB.vertices[i], 1e-6)) return false;
  }
  return true;
}

// ============================================================
// Analysis per pair (C00 vs C03 recomputed here for a self-contained deliverable; C00 vs C12
// is the new comparison)
// ============================================================

function analyzePair(facesA, facesB, modelAName, modelBName) {
  const correspondence = matchFaces(facesA, facesB);

  const matchedDetails = correspondence.matched.map(({ aIndex, bIndex, centroidDist, vertexOverlap }) => {
    const fa = facesA.find((f) => f.index === aIndex);
    const fb = facesB.find((f) => f.index === bIndex);
    const identical = facesIdentical(fa, fb);
    const tokA = lookupTokens(modelAName, aIndex);
    const tokB = lookupTokens(modelBName, bIndex);
    const tokensChanged = tokA && tokB && tokA.tokens && tokB.tokens ? JSON.stringify(tokA.tokens) !== JSON.stringify(tokB.tokens) : null;
    return {
      aIndex,
      bIndex,
      centroidDist,
      vertexOverlap,
      identical,
      ecChanged: fa.edgeCount !== fb.edgeCount,
      vcChanged: fa.vertexCount !== fb.vertexCount,
      secCountChanged: fa.secCount !== fb.secCount,
      b1LenChanged: fa.b1Len !== fb.b1Len,
      b2BodyChanged: JSON.stringify(normalizeB2Body(fa.b2Body)) !== JSON.stringify(normalizeB2Body(fb.b2Body)),
      tokensA: tokA,
      tokensB: tokB,
      tokensChanged,
    };
  });

  const addedDetails = correspondence.added.map((bIndex) => {
    const fb = facesB.find((f) => f.index === bIndex);
    const adjacentToA = computeAdjacency(fb, facesA);
    const adjacentToB = computeAdjacency(fb, facesB);
    return {
      bIndex,
      edgeCount: fb.edgeCount,
      vertexCount: fb.vertexCount,
      secCount: fb.secCount,
      b1Len: fb.b1Len,
      tokens: lookupTokens(modelBName, bIndex),
      adjacentToOriginalFaces: adjacentToA,
      adjacentToModelFaces: adjacentToB,
    };
  });

  return {
    modelAName,
    modelBName,
    faceCountA: facesA.length,
    faceCountB: facesB.length,
    faceCountDiff: facesB.length - facesA.length,
    matched: matchedDetails,
    removed: correspondence.removed,
    added: addedDetails,
    ambiguous: correspondence.ambiguous,
  };
}

const c00c03 = VERTEX_ANALYSIS['C00_cube_10mm_vs_C03_cube_fillet_1mm'];
const c00Faces = c00c03.facesA;
const c03Faces = c00c03.facesB;

console.log('\nEXP-038: NQ-028 discriminating test — C00 vs C03 (edge 1: +X/+Y) vs C12 (edge 2: -X/-Y)');
console.log('=========================================================================================\n');

const results = {};

console.log('--- C00 -> C03 (edge 1: fillet on +X/+Y edge; recomputed with EXP-037 tooling) ---');
const r03 = analyzePair(c00Faces, c03Faces, 'C00_cube_10mm', 'C03_cube_fillet_1mm');
results['C00_cube_10mm_vs_C03_cube_fillet_1mm'] = r03;
console.log(`Face count: ${r03.faceCountA} -> ${r03.faceCountB} (diff +${r03.faceCountDiff})`);
console.log(`Added: ${r03.added.map((a) => a.bIndex).join(',')}, Removed: [${r03.removed}], Ambiguous: ${r03.ambiguous.length}`);

console.log('\n--- C00 -> C12 (edge 2: fillet on -X/-Y edge; C12 parsed directly from real SLDPRT) ---');
const r12 = analyzePair(c00Faces, c12Faces, 'C00_cube_10mm', 'C12_cube_fillet_1mm_edge2');
results['C00_cube_10mm_vs_C12_cube_fillet_1mm_edge2'] = r12;
console.log(`Face count: ${r12.faceCountA} -> ${r12.faceCountB} (diff +${r12.faceCountDiff})`);
console.log(`Added: ${r12.added.map((a) => a.bIndex).join(',')}, Removed: [${r12.removed}], Ambiguous: ${r12.ambiguous.length}`);

function summarizeModel(r, aName, bName) {
  const newFace = r.added[0];
  const bToA = new Map(r.matched.map((m) => [m.bIndex, m.aIndex]));
  const adjacentC00Indices = new Set(
    newFace.adjacentToModelFaces.map((a) => a.index).filter((bIdx) => bToA.has(bIdx)).map((bIdx) => bToA.get(bIdx))
  );
  const changedTokenFaces = r.matched.filter((m) => m.tokensChanged === true).map((m) => m.aIndex);
  const unchangedTokenFaces = r.matched.filter((m) => m.tokensChanged === false).map((m) => m.aIndex);
  const structurallyChangedFaces = r.matched.filter((m) => m.ecChanged || m.vcChanged || m.secCountChanged || m.b1LenChanged).map((m) => m.aIndex);

  console.log(`\n${bName}:`);
  console.log(`  New face: B${newFace.bIndex} (ec=${newFace.edgeCount}, vc=${newFace.vertexCount}, secCount=${newFace.secCount})`);
  console.log(`  New face real within-model adjacency (>=2 shared vertices): ${JSON.stringify(newFace.adjacentToModelFaces)}`);
  console.log(`  Translated to C00 indices: [${[...adjacentC00Indices].join(',')}]`);
  console.log(`  C00 faces with structural change (ec/vc/secCount/b1Len): [${structurallyChangedFaces.join(',')}]`);
  console.log(`  C00 faces with CHANGED tokens (matched, structurally identical): [${changedTokenFaces.filter((i) => !structurallyChangedFaces.includes(i)).join(',')}]`);
  console.log(`  C00 faces with UNCHANGED tokens: [${unchangedTokenFaces.join(',')}]`);

  const orientOf = (idx) => {
    const t = lookupTokens(aName, idx);
    return t ? t.orientation : '?';
  };
  const unrelatedChanged = changedTokenFaces.filter((i) => !structurallyChangedFaces.includes(i));
  console.log(`  Orientation of token-changed-but-structurally-unmodified faces: [${unrelatedChanged.map((i) => `${i}:${orientOf(i)}`).join(', ')}]`);

  return {
    newFaceIndex: newFace.bIndex,
    adjacentC00Indices: [...adjacentC00Indices],
    structurallyChangedFaces,
    tokenChangedUnmodifiedFaces: unrelatedChanged,
    tokenChangedUnmodifiedOrientations: unrelatedChanged.map((i) => orientOf(i)),
    unchangedTokenFaces,
  };
}

console.log('\n=== PER-MODEL SUMMARY ===');
const summary03 = summarizeModel(r03, 'C00_cube_10mm', 'C03_cube_fillet_1mm');
const summary12 = summarizeModel(r12, 'C00_cube_10mm', 'C12_cube_fillet_1mm_edge2');

// ============================================================
// THE DISCRIMINATING CROSS-CHECK (NQ-028's actual question)
// ============================================================

console.log('\n\n=== NQ-028 CROSS-CHECK: does the token-changed-face set move with the edge? ===\n');
console.log('OBSERVATION (raw data, no causal claim):');
console.log(`  C03 (fillet on +X/+Y edge): token-changed-but-structurally-unmodified faces = ` +
  `[${summary03.tokenChangedUnmodifiedFaces.join(',')}] = orientations [${summary03.tokenChangedUnmodifiedOrientations.join(', ')}]`);
console.log(`  C12 (fillet on -X/-Y edge): token-changed-but-structurally-unmodified faces = ` +
  `[${summary12.tokenChangedUnmodifiedFaces.join(',')}] = orientations [${summary12.tokenChangedUnmodifiedOrientations.join(', ')}]`);

const sameIndexSet =
  JSON.stringify([...summary03.tokenChangedUnmodifiedFaces].sort()) === JSON.stringify([...summary12.tokenChangedUnmodifiedFaces].sort());
const sameOrientationSet =
  JSON.stringify([...summary03.tokenChangedUnmodifiedOrientations].sort()) === JSON.stringify([...summary12.tokenChangedUnmodifiedOrientations].sort());
const c12ChangedFacesMatchC12Adjacency =
  summary12.tokenChangedUnmodifiedFaces.length > 0 &&
  summary12.tokenChangedUnmodifiedFaces.every((i) => summary12.adjacentC00Indices.includes(i)) &&
  summary12.unchangedTokenFaces.every((i) => !summary12.adjacentC00Indices.includes(i));

console.log(`\n  Same face INDEX set changed in both models? ${sameIndexSet} (index-based/serialization-order explanation would predict TRUE)`);
console.log(`  Same ORIENTATION LABEL set changed in both models? ${sameOrientationSet} (Hypothesis B / global-feature-type-state would predict TRUE)`);
console.log(`  C12's changed faces are exactly its own real-adjacency set (as C03's were)? ${c12ChangedFacesMatchC12Adjacency} (Hypothesis A / spatial-adjacency would predict TRUE)`);

console.log('\nINTERPRETATION (see evidence file Section 7 for full anti-overclaim discussion):');
if (!sameIndexSet && !sameOrientationSet && c12ChangedFacesMatchC12Adjacency) {
  console.log('  The changed-face set moved to track the NEW physical edge location in C12, and remains');
  console.log('  exactly equal to C12\'s own real (vertex-computed) adjacency set, replicating the C03');
  console.log('  pattern at a different location. This is consistent with Hypothesis A (spatial/');
  console.log('  topological) and inconsistent with Hypothesis B (global/feature-type state) as stated.');
  console.log('  It is a correlational replication across n=2 edge locations, not a proof of mechanism.');
} else {
  console.log('  The changed-face set did NOT move to track the new edge location in the way Hypothesis A');
  console.log('  predicts. See per-field detail above for exactly what stayed fixed vs moved.');
}

results._nq028CrossCheck = {
  c03: summary03,
  c12: summary12,
  sameIndexSet,
  sameOrientationSet,
  c12ChangedFacesMatchC12Adjacency,
};

fs.writeFileSync(path.join(DIR, 'EXP038_RESULTS.json'), JSON.stringify(results, null, 2));
console.log('\n\nResults written to EXP038_RESULTS.json');
